name: money_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: any
  package_info_plus: ^7.0.0
  rename: ^3.0.2
  sticky_grouped_list: ^3.1.0
  syncfusion_flutter_charts: ^25.1.39+1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  image_path: "assets/icons/icon_1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  # generate localization files using l10n.yaml
  generate: true
